name: Update Flex endpoint

on:
    push:
        branches:
            - main

defaults:
    run:
        shell: bash

jobs:
    call-flex-update:
        uses: TheMilek/SyliusRecipes/.github/workflows/callable-flex-update.yaml@main
